name: Deploy to EC2 using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code dari GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH key (dari GitHub Secrets)
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 3.27.186.65 >> ~/.ssh/known_hosts
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      # Jalankan Docker Compose di EC2 melalui SSH
      - name: Deploy to EC2 using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.27.186.65 << 'EOF'
            cd /home/ubuntu/githubaction-python
            docker compose -f ./python/compose.yml up -d
          EOF
