name: Deploy to GCP using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          echo "Setting up SSH key"
          set -x
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_ALZI }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.31.192.61 >> ~/.ssh/known_hosts
        env:
          GCP_ALZI: ${{ secrets.GCP_ALZI }}

      - name: Deploy to GCP using SCP
        run: |
          echo "Connecting to GCP instance"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./my-app aljisaptiadi@34.31.192.61:/home/aljisaptiadi/react-js
