name: Deploy to EC2 using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          echo "Setting up SSH key"
          set -x  
          mkdir -p ~/.ssh
          ls -ld ~/.ssh

          echo "${{ secrets.GCP_ALZI }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -l ~/.ssh

          ssh-keyscan -H 34.31.192.61 >> ~/.ssh/known_hosts
          ls -l ~/.ssh/known_hosts
        env:
          GCP_ALZI: ${{ secrets.GCP_ALZI }}
