name: Deploy to GCP using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH key
      - name: Set up SSH key
        run: |
          echo "Setting up SSH key"
          set -x
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_ALZI }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.46.29.47 >> ~/.ssh/known_hosts
        env:
          GCP_ALZI: ${{ secrets.GCP_ALZI }}

      # SCP file dari GitHub ke GCP
      - name: Deploy to GCP using SCP
        run: |
          echo "Connecting to GCP instance"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ${{ github.workspace }}/my-app aljisaptiadi@34.46.29.47:/home/aljisaptiadi/react-app
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ${{ github.workspace }}/mongo aljisaptiadi@34.46.29.47:/home/aljisaptiadi/node-app
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa aljisaptiadi@34.46.29.47 << 'EOF'
          echo 'Restart React'
          sudo su
          cd /home/aljisaptiadi/react-app
          docker stop react-app;docker rm react-app;docker rmi react-app
          docker build -t react-app .
          docker run --name react-app -d -p 3000:3000 react-app
          echo 'Restart Nodejs'
          cd /home/aljisaptiadi/node-app
          docker stop node-app;docker rm node-app;docker rmi node-app
          docker build -t node-app .
          docker run --name node-app -d -p 5000:5000 node-app