name: Docker Compose CI

on:
  push:
    branches:
      - UAT  # Memicu workflow untuk perubahan apapun di branch UAT
  pull_request:
    branches:
      - UAT



jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Pull the latest changes (optional, because checkout sudah melakukannya)
    -   name: Auto Pull latest changes
        run: git pull origin UAT

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and run Docker Compose
      - name: Run Docker Compose
        run: |
          docker compose -f ./python/compose.yml up -d
          
      # Check status of containers (optional)
      - name: List running containers
        run: docker ps

      # (Optional) Clean up and stop containers
      - name: Stop and remove containers
        run: docker compose -f ./python/compose.yml down